#database: sqlite, mysql
data_mode: "sqlite"
mysql:
  url: "host:port/database_name"
  username: "yourUsername"
  password: "yourPassword"

# This will add a crate to the head of the mob, and will be dropped when the mob is killed
# Only works for mobs that spawn naturally in the world
crate_spawn_on_entity:
  enabled: true
  modify_health_multiplier: 3
  # Premade crates
  crates_chance:
    rare: 0.1 # 1%
    epic: 0.05 # 0.5%
    legendary: 0.01 # 0.1%

# Gui config
gui:
  size: 27
  title: "&eRewards"
  daily:
    enabled: true
    name: "&6Daily Rewards"
    lore:
    - "&7You will receive a random item "
    - "&7You can claim in: %daily%"
    material: "CHEST_MINECART"
    slot: 0
  streak:
    enabled: true
    name: "&2Streak Connection"
    lore:
    - "&7You will receive a reward for each connection"
    - "&7Current streak: %streak%"
    - "&7You will receive:"
    - "&7For each day: 1 money"
    material: "EMERALD"
    slot: 2
  vote:
    enabled: true
    name: "&3Vote Rewards"
    lore:
    - "&7You have &c%vote%&7 votes"
    - "&7Use /vote to how to vote"
    material: "NETHERITE_UPGRADE_SMITHING_TEMPLATE"
    slot: 4
  playtime:
    enabled: true
    name: "&ePlaytime Rewards"
    lore:
    - "&7You have played for &e%playtime%"
    - "&7You will receive a reward if you are in the top 3"
    - "&7Weekly check: Sunday 20:00 hs"
    material: "CLOCK"
    slot: 6
  referrals:
    enabled: true
    name: "&eReferral Rewards"
    lore:
    - "&7You have referred &a%referrals%&7 players"
    - "&7Your code is: &6%code%"
    - "&7You will receive a reward for each referral"
    - "&7New Players can use /refer <code> to use your code and receive a reward"
    - "&8Rewards:"
    material: "TOTEM_OF_UNDYING"
    slot: 8

# Daily rewards
# This will give the player a reward for logging in daily
# Where a random item will be given to the player
daily:
  blacklist:
  - "COMMAND_BLOCK"
  - "BARRIER"
  - "LIGHT"
  - "AIR"
  - "BEDROCK"
  - "CHAIN_COMMAND_BLOCK"
  - "REPEATING_COMMAND_BLOCK"
  - "COMMAND_BLOCK_MINECART"
  - "STRUCTURE_BLOCK"
  - "STRUCTURE_VOID"
  - "JIGSAW"
  - "SPAWNER"

# Reward player for streak connection to the server
streak_connection:
  rewards:
    1: #This number is the amount of streaks connections - 1 means that this will apply allways
      message: ""
      commands:
      - eco add %player% %streak% # this will give the player the amount of money equal to their streak
      broadcast: ""
      # So with this example, the player will receive 1 money for each streak connection each time they connect to the server
    # 14: #So this will apply when the player has 14 streak connections or more
    #   message: "&7"
    #   broadcast: "&7%player% has reached 14 streak connections! They received a bonus reward!"
    #   commands: 
    #   - eco give %player% 1400
    # 21:
    #   message: "&7"
    #   commands:
    #   - eco give %player% 2100
    # 28:
    #   message: "&7"
    #   commands:
    #   - eco give %player% 2800    

# Vote rewards
vote:
  rewards:
    1: #Example
      chance: 100 # 100%
      message: "Thanks for voting! You will receive: " #this message will be sended to the player
      broadcast: ""
      commands:
      - eco give %player% 5
    2: #Support multiple rewards - This number is not the the amount of votes!
      chance: 10 # 10%
      message: ""
      broadcast: "Luck is on %player%'s side! They received a bonus reward!"
      commands:
      - eco give %player% 100
    3:
      chance: 1 # 0%
      message: ""
      broadcast: "Omg! %player% is so lucky! They received a bonus reward of voting!"
      commands:
      - eco give %player% 500

# This is a weekly check
# We just read the playtime of the player on the server
# So we dont modify those values and the time never resets
# Just reward the most active players
playtime:
  check_on: SUNDAY
  at: 20 #hs
  rewards:
    1: #player top 1
      message: "" #this message will be sended to the player
      broadcast: "%player% is the most active player on the server! They received a bonus reward!"
      commands:
      - eco give %player% 5
    2: #top 2
      message: ""
      broadcast: ""
      commands:
      - eco give %player% 10
    3: #top 3
      message: ""
      broadcast: ""
      commands:
      - eco give %player% 15


# Referral rewards
referral:
  no_count_old_players: true #If true, old players cant use a referral code (If his playtime is more than 1 hour)
  after_how_much_playtime: 30 #If the new player has played more than 30 minutes, the referred player will receive the reward
  #The referrer will receive the reward anyway.
  rewards:
    to_referrer:
      message: "Thanks for referring a new player! You will receive: " #this message will be sended to the player
      commands:
      - eco give %player% 5
      # add tokens or something especial
    to_referred:
      message: "Thanks for using a referral code! You will receive: " #this message will be sended to the player
      commands:
      - eco give %player% 100
      # - add tokens or something especial
    on_buy_commands:
      message: "A referred player by you, have purchased on the store, You will receive: ? "
      commands:
      # you can use a command (maybe on your store) to give a reward to the referrer
      # you must use for example: /referrals addbuy <buyer> <amount>
      # If the buyer has used a referral code, the referrer will receive the next reward
      # If the buyer has not used a referral code, the command will not be executed
      # The amount is the amount of that you used in the command
      # Take care, the referrer maybe will be offline, we dont queue the rewards.
      - eco give %player% %amount% # This will work even if the player is offline or online
      - give %player% diamond 1 # This will no work if the players is offline
      # - tokens add %player% %amount%
