main: com.ar.askgaming.rewards.RewardsPlugin
name: Rewards
version: 1.0
api-version: 1.21
author: AskGaming
soft-depend: [VotifierPlus]
commands:
  rewards:
    description: Shows the rewards
    usage: /rewards
  crate:
    description: Opens a crate
    permission: rewards.crate.admin
    usage: /crate
  vote:
    description: Vote for the server
    usage: /vote

